export const members = [
  // HARDWARE
  {
    name: "Bart Backer",
    image: "/assets/profile-images/BartBacker.jpg",
    role: "Subgroup Lead",
    subgroup: "Hardware",
    linkedin: "https://www.linkedin.com/in/bart-backer",
  },
  {
    name: "Carm Ypil Hermosilla",
    image: "/assets/profile-images/sample-pfp.png",
    role: "Engineer",
    subgroup: "Embedded",
    linkedin: "https://www.linkedin.com/in/carm-hermosilla/",
  },
  // EMBEDDED SYSTEMS
  {
    name: "Anthony Chen",
    image: "/assets/profile-images/AnthonyChen.jpg",
    role: "Subgroup Lead",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/anthony-chen-639750174/",
  },
  {
    name: "Alex Ikeda",
    image: "/assets/profile-images/sample-pfp-2.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/alexikeda/",
  },
  // WASTE RECOGNITION
  {
    name: "Badrish Ananth",
    image: "/assets/profile-images/BadrishAnanth.jpg",
    role: "Team Lead, Subgroup Lead",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/badrish-ananth-8a6311231/",
  },
  {
    name: "Arya Mhaiskar",
    image: "/assets/profile-images/AryaMhaiskar.jpeg",
    role: "Subgroup Lead",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/arya-mhaiskar/",
  },
  {
    name: "Nathan Pietrantonio",
    image: "/assets/profile-images/NathanPietrantonio.jpg",
    role: "Subgroup Lead",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/arya-mhaiskar/",
  },
  {
    name: "Varun Sunkavalli",
    image: "/assets/profile-images/VarunSunkavalli.png",
    role: "Researcher",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/varun-sunkavalli/",
  },
  // API
  {
    name: "Jason Zenarosa",
    image: "/assets/profile-images/sample-pfp-2.png",
    role: "Subgroup Lead",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/jasonzenarosa",
  },
  {
    name: "Manjot Singh",
    image: "/assets/profile-images/ManjotSingh.jpg",
    role: "Subgroup Lead",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/manjot-singh18",
  },
  {
    name: "Geric Capili",
    image: "/assets/profile-images/sample-pfp-2.png",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/gericcapili/",
  },
  {
    name: "Rebecca Ahn",
    image: "/assets/profile-images/RebeccaAhn.jpg",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/rebecca-ahn/",
  },
  {
    name: "Brianna Steier",
    image: "/assets/profile-images/BriannaSteier.jpg",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/briannasteier",
  },
  {
    name: "Cali Kuang",
    image: "/assets/profile-images/CaliKuang.jpg",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/cali-kuang/",
  },
  // WEB AND MOBILE
  {
    name: "Evan Servito",
    image: "/assets/profile-images/EvanServito.jpg",
    role: "Subgroup Lead",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/evan-servito/",
  },
  {
    name: "Zion Mateo",
    image: "/assets/profile-images/ZionMateo.jpg",
    role: "Subgroup Lead",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/zionmateo/",
  },
  {
    name: "Sophia Tran",
    image: "/assets/profile-images/SophiaTran.jpg",
    role: "Developer",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/sophia-belle-tran/",
  },
];
