export const members = [
  // HARDWARE
  {
    name: "Bart Backer",
    image: "/assets/profile-images/BartBacker.jpg",
    role: "Subgroup Lead",
    subgroup: "Hardware",
    linkedin: "https://www.linkedin.com/in/bart-backer",
  },
  {
    name: "Adrianne Chang",
    image: "/assets/profile-images/AdrianneChang.jpg",
    role: "Engineer",
    subgroup: "Hardware",
    linkedin:"https://www.linkedin.com"
  },
  {
    name: "Youngwoo Chang",
    image: "/assets/profile-images/sample-pfp-2.png",
    role: "Engineer",
    subgroup: "Hardware",
    linkedin:"https://www.linkedin.com"
  },
  {
    name: "Philip Hopkins",
    image: "/assets/profile-images/PhilipHopkins.png",
    role: "Engineer",
    subgroup: "Hardware",
    linkedin:"https://www.linkedin.com/in/philip-hopkins-a173612b5/"
  },
  {
    name: "Jenny Liang",
    image: "/assets/profile-images/JennyLiang.png",
    role: "Engineer",
    subgroup: "Hardware",
    linkedin:"https://www.linkedin.com/in/jennyliang2005/"
  },
  {
    name: "Mihir Mehta",
    image: "/assets/profile-images/MihirMehta.png",
    role: "Engineer",
    subgroup: "Hardware",
    linkedin:"https://www.linkedin.com/in/mihir-mehta-a86042229/"
  },
  {
    name: "Samith Varamballi",
    image: "/assets/profile-images/SamithVaramballi.png",
    role: "Engineer",
    subgroup: "Hardware",
    linkedin:"https://www.linkedin.com/in/samith-varamballi/"
  },
  {
    name: "Chad Wong",
    image: "/assets/profile-images/ChadWong.png",
    role: "Engineer",
    subgroup: "Hardware",
    linkedin:"http://www.linkedin.com/in/chad-wong-65a076321/"
  },
  {
    name: "Hudson Wheeler",
    image: "/assets/profile-images/HudsonWheeler.png",
    role: "Engineer",
    subgroup: "Hardware",
    linkedin:"http://www.linkedin.com/in/hudson-wheeler-38786526a/"
  },
  // EMBEDDED SYSTEMS
  {
    name: "Anthony Chen",
    image: "/assets/profile-images/AnthonyChen.jpg",
    role: "Subgroup Lead",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/anthony-chen-639750174/",
  },
  {
    name: "Priya Patel",
    image: "/assets/profile-images/PriyaPatel.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/priyapa/",
  },
  {
    name: "Jeffrey Frederick",
    image: "/assets/profile-images/sample-pfp-2.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/jeffreyfrederick1/",
  },
  {
    name: "Vathsan Sankaranarayanan",
    image: "/assets/profile-images/VathsanSankaranarayanan.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/srivathsan-sankaranarayanan-29659b197/",
  },
  {
    name: "Jerald Adriano",
    image: "/assets/profile-images/JeraldAdriano.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/jeraldadriano/",
  },
  {
    name: "Ryan Su",
    image: "/assets/profile-images/RyanSu.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/ryan-m-su/",
  },
  {
    name: "Hussain Mahuvawala",
    image: "/assets/profile-images/sample-pfp-2.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/hm1711/",
  },
  {
    name: "Andy Choi",
    image: "/assets/profile-images/AndyChoi.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/andy-choi-2b503a27b/",
  },
  {
    name: "Krish Mehta",
    image: "/assets/profile-images/KrishMehta.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/krish-n-mehta/",
  },
  {
    name: "Eric Liu",
    image: "/assets/profile-images/EricLiu.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/eriliu/",
  },
  {
    name: "Oscar Rodriguez",
    image: "/assets/profile-images/OscarRodriguez.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/alwaysoscar/",
  },
  {
    name: "Zarin Hasan",
    image: "/assets/profile-images/ZarinHasan.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/zarin-hasan-20983522b/",
  },
  {
    name: "Alex Ikeda",
    image: "/assets/profile-images/sample-pfp-2.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/alexikeda/",
  },
  {
    name: "Carm Hermosilla",
    image: "/assets/profile-images/sample-pfp.png",
    role: "Engineer",
    subgroup: "Embedded Systems",
    linkedin: "https://www.linkedin.com/in/carm-hermosilla/",
  },
  // WASTE RECOGNITION
  {
    name: "Badrish Ananth",
    image: "/assets/profile-images/BadrishAnanth.jpg",
    role: "Team Lead, Subgroup Lead",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/badrish-ananth-8a6311231/",
  },
  {
    name: "Arya Mhaiskar",
    image: "/assets/profile-images/AryaMhaiskar.jpeg",
    role: "Subgroup Lead",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/arya-mhaiskar/",
  },
  {
    name: "Nathan Pietrantonio",
    image: "/assets/profile-images/NathanPietrantonio.jpg",
    role: "Subgroup Lead",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/nathanlp/",
  },
  {
    name: "Rebecca Su",
    image: "/assets/profile-images/sample-pfp.png",
    role: "Researcher",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/surebecca/",
  },
  {
    name: "Aditya Agrawal",
    image: "/assets/profile-images/AdityaAgrawal.png",
    role: "Researcher",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/aagrawal05/",
  },
  {
    name: "Lahari Yallapragada",
    image: "/assets/profile-images/LahariYallapragada.png",
    role: "Researcher",
    subgroup: "Waste Recognition",
    linkedin: "http://www.linkedin.com/in/lahariyallapragada/",
  },
  {
    name: "Varun Sunkavalli",
    image: "/assets/profile-images/VarunSunkavalli.png",
    role: "Researcher",
    subgroup: "Waste Recognition",
    linkedin: "https://www.linkedin.com/in/varun-sunkavalli/",
  },
  // API
  {
    name: "Jason Zenarosa",
    image: "/assets/profile-images/JasonZenarosa.png",
    role: "Subgroup Lead",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/jasonzenarosa",
  },
  {
    name: "Manjot Singh",
    image: "/assets/profile-images/ManjotSingh.jpg",
    role: "Subgroup Lead",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/manjot-singh18",
  },
  {
    name: "Geric Capili",
    image: "/assets/profile-images/GericCapili.png",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/gericcapili/",
  },
  // {
  //   name: "Rebecca Ahn",
  //   image: "/assets/profile-images/RebeccaAhn.jpg",
  //   role: "Developer",
  //   subgroup: "API",
  //   linkedin: "https://www.linkedin.com/in/rebecca-ahn/",
  // },
  {
    name: "Brianna Steier",
    image: "/assets/profile-images/BriannaSteier.jpg",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/briannasteier",
  },
  {
    name: "Cali Kuang",
    image: "/assets/profile-images/CaliKuang.jpg",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/cali-kuang/",
  },
  {
    name: "Alvin Phan",
    image: "/assets/profile-images/AlvinPhan.png",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/alvinphan3/",
  },
  {
    name: "Kali Daschoudhary",
    image: "/assets/profile-images/sample-pfp.png",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com",
  },
  {
    name: "Steven Lee",
    image: "/assets/profile-images/StevenLee.png",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/steven-lee-55353b295/",
  },
  {
    name: "Arnav Gosain",
    image: "/assets/profile-images/ArnavGosain.png",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/arnav-gosain/",
  },
  {
    name: "Nathan Che",
    image: "/assets/profile-images/NathanChe.png",
    role: "Developer",
    subgroup: "API",
    linkedin: "https://www.linkedin.com/in/nathan-che1/",
  },
  // WEB AND MOBILE
  // {
  //   name: "Evan Servito",
  //   image: "/assets/profile-images/EvanServito.jpg",
  //   role: "Subgroup Lead",
  //   subgroup: "Web & Mobile",
  //   linkedin: "https://www.linkedin.com/in/evan-servito/",
  // },
  {
    name: "Zion Mateo",
    image: "/assets/profile-images/ZionMateo.jpg",
    role: "Subgroup Lead",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/zionmateo/",
  },
  {
    name: "Sophia Tran",
    image: "/assets/profile-images/SophiaTran.jpg",
    role: "Subgroup Lead",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/sophia-belle-tran/",
  },
  {
    name: "Cyrus Buffington",
    image: "/assets/profile-images/CyrusBuffington.png",
    role: "Developer",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/cyrusbuffington/",
  },
  {
    name: "Ethan Santos",
    image: "/assets/profile-images/EthanSantos.png",
    role: "Developer",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/ethanmadeit/",
  },
  {
    name: "Hearty Parrenas",
    image: "/assets/profile-images/HeartyParrenas.png",
    role: "Developer",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/hearty-parrenas/",
  },
  {
    name: "Kaylee Doliente",
    image: "/assets/profile-images/KayleeDoliente.png",
    role: "Designer",
    subgroup: "Web & Mobile",
    linkedin: "http://www.linkedin.com/in/kayleedoliente/",
  },
  {
    name: "Grace Jong",
    image: "/assets/profile-images/GraceJong.png",
    role: "Designer",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/gracejong/",
  },
  {
    name: "Angie Xetey",
    image: "/assets/profile-images/AngieXetey.png",
    role: "Designer",
    subgroup: "Web & Mobile",
    linkedin: "https://www.linkedin.com/in/angie-xetey/",
  },
];
